dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB

      role: transform
      schema: DEV
      threads: 1
      type: snowflake
   
      warehouse: COMPUTE_WH
      user: "{{env_var('user')}}"
      password:  "{{env_var('pass')}}"
  target: dev
