dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      password: {{env_var('gpass')}}
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: {{env_var('guser')}}
      warehouse: COMPUTE_WH      
  target: dev
