dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      # password:  "{{env_var('gpass')}}"
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      # user: "{{env_var('guser')}}"
      warehouse: COMPUTE_WH
      
      
  target: dev
