dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      user: "dbt"
      password: "dbtPassword123"
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      
      warehouse: COMPUTE_WH
  target: dev
