dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      user: suswala
      password: Snowflakedemo#1
      role: ACCOUNTADMIN
      schema: DEV
      threads: 1
      type: snowflake
      
      warehouse: COMPUTE_WH
  target: dev
