dbtlearn:
  outputs:
    dev:
      account: KZCOZLS-IV75894
      database: AIRBNB
      password: Snowflakedemo#1
      role: SYSADMIN
      schema: DEV
      threads: 1
      type: snowflake
      user: suswala
      warehouse: COMPUTE_WH
  target: dev
