# This is a basic workflow to help you get started with Actions
name: docker_dbt
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: xemuliam/dbt
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
    #   - name: change directory
    #     run: cd $GITHUB_WORKSPACE
      - name: Dbt version
        run: dbt --version
        
      - name: Install git
        run: |
            apt-get update
            apt-get install -y git
            git --version
        
      - name: DBT auto add seeds
        run: |   
            pwd
            git init
            git remote add origin https://github.com/uswal/DBT/
            git config --global init.defaultBranch main
            git config --global --add safe.directory /__w/DBT/DBT
            #cd /home/runner/work/DBT/DBT
            #git remote set-url origin https://github.com/uswal/dbt.git
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            touch "$(date +'%Y%m%d%H%M%S').txt"
            git add .
            git commit -m "Generate and push a file"
        
      - name: Push
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{secrets.token}}
        


    # git clone https://github.com/uswal/DBT.git         
      
    #cd ./DBT
    # eval $(ssh-agent -s)
    # chmod 700 ./Auth/id_ed25519
    # ssh-add ./Auth/id_ed25519   
    # git clone git@github.com:uswal/DBT.git