name: Generate and Push File

on:
  push:
    branches:
      - main  # Change to your main branch name if needed

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    #   - name: Generate File
    #     run: |
    #       # Add commands here to gener
    #       git add .
    #       git commit -m "test"
    #       git push originate your file
    #       echo "This is a generated file." > generated.txt

      - name: Commit and Push Generated File
        run: |
            echo "This is a generated file." > generated.txt
            echo "hi"
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            chmod 700 ./Auth/id_ed25519
            eval $(ssh-agent -s)
            ssh-add ./Auth/id_ed25519
            git remote set-url origin https://github.com/uswal/dbt
            git checkout main
            git add .
            git commit -m "test"
            git push origin main


    #   - name: Push
    #     uses: ad-m/github-push-action@master
    #     with:
    #         github_token: ${{secrets.token}}

        
          