name: Generate and Push File

on:
  push:
    branches:
      - main  # Change to your main branch name if needed

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate File
        run: |
          # Add commands here to generate your file
          echo "This is a generated file." > generated.txt

      - name: Commit and Push Generated File
        run: |
          git config --global user.name 'Ujjawal'
          git config --global user.email 'uswalanand1999@gmail.com'
          git remote set-url origin https://github.com/${{ github.repository }}
          eval $(ssh-agent -s)
          chmod 700 ./Auth/id_ed25519
          ssh-add ./Auth/id_ed25519   
          git add generated.txt
          git commit -m "Generate and push a file"
          git push

      - name: Push
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{secrets.token}}

        
          